# Generated by Django 3.2.7 on 2021-11-19 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='House')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('nin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(error_messages={'blank': 'can no be blank. fill it now!'}, max_length=60)),
                ('lname', models.CharField(help_text='Its like a family name', max_length=60)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('afile', models.FileField(upload_to='Files/%Y/%m/%d/')),
                ('afilepath', models.FilePathField(match='*.txt', path='/home/userun/Documents/RealEstate/Django/media')),
                ('profile', models.ImageField(default='default.jpg', upload_to='ProfilePics')),
                ('size', models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10, verbose_name='body size')),
                ('height', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('etime', models.DateField(default=datetime.date.today)),
                ('etzone', models.DateTimeField(default=django.utils.timezone.now)),
                ('fazno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ipadd', models.GenericIPAddressField(default='::ffff:10.10.10.10', unpack_ipv4='True')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Peaple',
                'db_table': '',
                'ordering': ['?', 'height'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topname', models.CharField(max_length=50)),
                ('ingredientschoice', models.CharField(blank=True, choices=[('meat', 'Meat'), ('veg', 'Veg'), ('grass', 'Grass')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.ManyToManyField(to='examples.Topping')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['lname', 'fname'], name='examples_pe_lname_e67d34_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['fname'], name='fname_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.group'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.person'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.manufacturer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.question'),
        ),
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['lname'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('examples.person',),
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
    ]
