# Generated by Django 3.2.7 on 2021-11-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'ordering': ['?', 'height'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='afilepath',
        ),
    ]
