module.exports = {
  purge: [],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {
      accessibility: ["responsive", "focus-within", "focus"],
      alignContent: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      alignItems: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      alignSelf: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      animation: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      appearance: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropBlur: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropBrightness: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropContrast: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropFilter: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropGrayscale: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropHueRotate: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropInvert: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropSaturate: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backdropSepia: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundAttachment: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundBlendMode: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundClip: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundImage: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundPosition: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundRepeat: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundSize: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      backgroundOrigin: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      blur: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderCollapse: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderRadius: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderStyle: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      borderWidth: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      boxDecorationBreak: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      boxShadow: ["responsive", "group-hover", "focus-within", "hover", "focus"],
      boxSizing: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      brightness: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      clear: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      container: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      contrast: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      cursor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      display: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      divideColor: ["responsive", "dark"],
      divideOpacity: ["responsive", "dark"],
      divideStyle: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      divideWidth: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      dropShadow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fill: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      filter: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      flex: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      flexDirection: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      flexGrow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      flexShrink: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      flexWrap: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      float: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontFamily: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontSize: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontSmoothing: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontStyle: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontVariantNumeric: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      fontWeight: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gap: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gradientColorStops: ["responsive", "dark", "hover", "focus"],
      grayscale: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridAutoColumns: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridAutoFlow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridAutoRows: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridColumn: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridColumnEnd: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridColumnStart: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridRow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridRowEnd: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridRowStart: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridTemplateColumns: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      gridTemplateRows: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      height: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      hueRotate: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      inset: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      invert: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      isolation: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      justifyContent: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      justifyItems: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      justifySelf: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      letterSpacing: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      lineHeight: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      listStylePosition: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      listStyleType: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      margin: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      maxHeight: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      maxWidth: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      minHeight: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      minWidth: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      mixBlendMode: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      objectFit: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      objectPosition: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      opacity: ["responsive", "group-hover", "focus-within", "hover", "focus"],
      order: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      outline: ["responsive", "focus-within", "focus"],
      overflow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      overscrollBehavior: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      padding: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      placeContent: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      placeItems: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      placeSelf: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      placeholderColor: ["responsive", "dark", "focus"],
      placeholderOpacity: ["responsive", "dark", "focus"],
      pointerEvents: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      position: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      resize: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      ringColor: ["responsive", "dark", "focus-within", "focus"],
      ringOffsetColor: ["responsive", "dark", "focus-within", "focus"],
      ringOffsetWidth: ["responsive", "focus-within", "focus"],
      ringOpacity: ["responsive", "dark", "focus-within", "focus"],
      ringWidth: ["responsive", "focus-within", "focus"],
      rotate: ["responsive", "hover", "focus"],
      saturate: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      scale: ["responsive", "hover", "focus"],
      sepia: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      skew: ["responsive", "hover", "focus"],
      space: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      stroke: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      strokeWidth: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      tableLayout: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      textAlign: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      textColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      textDecoration: ["responsive", "group-hover", "focus-within", "hover", "focus"],
      textOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      textOverflow: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      textTransform: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transform: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transformOrigin: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transitionDelay: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transitionDuration: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transitionProperty: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      transitionTimingFunction: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      translate: ["responsive", "hover", "focus"],
      userSelect: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      verticalAlign: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      visibility: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      whitespace: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      width: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      wordBreak: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
      zIndex: ["responsive", "focus-within", "focus"],
    },
  },
  plugins: [],
};
